-- ====================================================================
-- StreamVista Enterprise Cloud V2 - Sovereign Database Schema
-- Target Engine: Oracle Autonomous Database (ATP / ADW 19c/21c)
-- ====================================================================

-- 1. ROLES LOOKUP TABLE
CREATE TABLE roles (
    role_id VARCHAR2(30) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO roles (role_id, name, description) VALUES ('ADMIN', 'System Administrator', 'Operations staff with global ledger clearance');
INSERT INTO roles (role_id, name, description) VALUES ('CREATOR', 'Content Creator / Seller', 'Independent studios and international sales agents');
INSERT INTO roles (role_id, name, description) VALUES ('BUYER', 'Acquisition Buyer / Distributor', 'Streaming platforms, TV networks, and theatrical buyers');

-- 2. USERS TABLE
CREATE TABLE users (
    user_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role_id VARCHAR2(30) NOT NULL,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, ACTIVE, SUSPENDED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
    CONSTRAINT chk_user_status CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED'))
);

CREATE INDEX idx_users_email ON users(email);

-- 3. CREATOR PROFILES
CREATE TABLE creator_profiles (
    profile_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19, 0) NOT NULL UNIQUE,
    company_name VARCHAR2(255) NOT NULL,
    contact_name VARCHAR2(255) NOT NULL,
    website VARCHAR2(255),
    catalog_size NUMBER(10, 0) DEFAULT 0,
    wallet_address VARCHAR2(255),
    verified_status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_creator_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_creator_verified CHECK (verified_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 4. BUYER PROFILES
CREATE TABLE buyer_profiles (
    profile_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19, 0) NOT NULL UNIQUE,
    company_name VARCHAR2(255) NOT NULL,
    contact_name VARCHAR2(255) NOT NULL,
    website VARCHAR2(255),
    acquisition_budget NUMBER(19, 2) DEFAULT 0.00,
    verified_status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_buyer_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_buyer_verified CHECK (verified_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 5. ONBOARDING BRIDGE APPLICATIONS (REGISTRATIONS)
CREATE TABLE approvals (
    approval_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR2(50) NOT NULL, -- 'BRIDGE_REGISTRATION', 'FILM_METADATA'
    target_id NUMBER(19, 0) NOT NULL,
    reviewer_email VARCHAR2(255),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED
    comments VARCHAR2(1000),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_approval_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 6. FILMS CATALOG
CREATE TABLE films (
    film_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    synopsis VARCHAR2(4000) NOT NULL,
    genre VARCHAR2(100) NOT NULL,
    release_year NUMBER(4, 0) NOT NULL,
    duration_minutes NUMBER(5, 0) NOT NULL,
    languages VARCHAR2(500) NOT NULL, -- Comma separated language list
    subtitles VARCHAR2(500),          -- Comma separated subtitle list
    rights VARCHAR2(1000) NOT NULL,    -- Comma separated licensing structures (e.g. SVOD, TVOD)
    uploaded_by VARCHAR2(255) NOT NULL, -- Creator email association
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED
    review_notes VARCHAR2(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_film_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_films_status ON films(status);
CREATE INDEX idx_films_creator ON films(uploaded_by);

-- 7. ASSETS (OCI OBJECT STORAGE MAPPINGS)
CREATE TABLE assets (
    asset_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id NUMBER(19, 0) NOT NULL,
    category VARCHAR2(50) NOT NULL, -- Videos, Audio, Images, Contracts, Certificates, Documents, Screeners, Delivery Packages
    file_name VARCHAR2(255) NOT NULL,
    oci_object_name VARCHAR2(1000) NOT NULL, -- The unique key path inside the OCI bucket
    mime_type VARCHAR2(150) NOT NULL,
    file_size_bytes NUMBER(19, 0) NOT NULL,
    uploaded_by VARCHAR2(255) NOT NULL,
    md5_checksum VARCHAR2(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_asset_film FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT chk_asset_category CHECK (category IN ('Videos', 'Audio', 'Images', 'Contracts', 'Certificates', 'Documents', 'Screeners', 'Delivery Packages'))
);

CREATE INDEX idx_assets_film ON assets(film_id);

-- 8. SUBMISSIONS (AUDIT COMPLIANCE)
CREATE TABLE submissions (
    submission_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id NUMBER(19, 0) UNIQUE NOT NULL,
    blockchain_hash VARCHAR2(64) NOT NULL, -- Hash linking metadata submission to autonomous ledger
    status VARCHAR2(30) DEFAULT 'SUBMITTED' NOT NULL,
    verified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_submission_film FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
);

-- 9. SCREENER REQUESTS & CODES
CREATE TABLE screeners (
    screener_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id NUMBER(19, 0) NOT NULL,
    buyer_email VARCHAR2(255) NOT NULL,
    buyer_company VARCHAR2(255) NOT NULL,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REVOKED, EXPIRED
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    expires_at TIMESTAMP,
    views_remaining NUMBER(5, 0) DEFAULT 5 NOT NULL,
    watermark_text VARCHAR2(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_screener_film FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT chk_screener_status CHECK (status IN ('PENDING', 'APPROVED', 'REVOKED', 'EXPIRED'))
);

CREATE INDEX idx_screeners_buyer ON screeners(buyer_email);

-- 10. SCREENER ACCESS / TELEMETRY LOGS
CREATE TABLE screener_access_logs (
    log_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screener_id NUMBER(19, 0) NOT NULL,
    viewer_email VARCHAR2(255) NOT NULL,
    action VARCHAR2(100) NOT NULL, -- CLICKED_PLAY, COMPLETED_VIEW, HEARTBEAT
    ip_address VARCHAR2(45) NOT NULL,
    system_details VARCHAR2(500),
    playback_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_access_screener FOREIGN KEY (screener_id) REFERENCES screeners(screener_id) ON DELETE CASCADE
);

-- 11. DEALS (LICENSING OPPORTUNITIES)
CREATE TABLE deals (
    deal_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id NUMBER(19, 0) NOT NULL,
    film_title VARCHAR2(255) NOT NULL,
    creator_email VARCHAR2(255) NOT NULL,
    buyer_email VARCHAR2(255) NOT NULL,
    buyer_company VARCHAR2(255) NOT NULL,
    rights_type VARCHAR2(100) NOT NULL, -- SVOD, TVOD, AVOD, PayTV Broadcast, Theatrical
    territories VARCHAR2(1000) NOT NULL, -- Comma-separated region list
    exclusivity NUMBER(1, 0) DEFAULT 1 NOT NULL, -- 0 = False, 1 = True
    duration_years NUMBER(3, 0) NOT NULL,
    price NUMBER(19, 2) NOT NULL,
    status VARCHAR2(30) DEFAULT 'PROFFERED' NOT NULL, -- PROFFERED, COUNTERED, ACCEPTED, REJECTED, EXECUTED
    oracle_contract_id VARCHAR2(255),
    signed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_deal_film FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT chk_deal_status CHECK (status IN ('PROFFERED', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'EXECUTED'))
);

CREATE INDEX idx_deals_buyer ON deals(buyer_email);
CREATE INDEX idx_deals_creator ON deals(creator_email);

-- 12. NEGOTIATIONS DRAFT CHRONOLOGY (AUDIT TRAILS FOR DEALS)
CREATE TABLE negotiations (
    negotiation_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id NUMBER(19, 0) NOT NULL,
    sender VARCHAR2(30) NOT NULL,       -- CREATOR, BUYER, SYSTEM
    sender_name VARCHAR2(255) NOT NULL,
    action VARCHAR2(50) NOT NULL,       -- OFFER_CREATED, COUNTER_PROPOSED, OFFER_ACCEPTED, CONTRACT_SIGNED
    price NUMBER(19, 2) NOT NULL,
    note VARCHAR2(2000),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_neg_deal FOREIGN KEY (deal_id) REFERENCES deals(deal_id) ON DELETE CASCADE
);

-- 13. EXECUTED CONTRACTS
CREATE TABLE contracts (
    contract_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id NUMBER(19, 0) NOT NULL UNIQUE,
    creator_signature VARCHAR2(100) NOT NULL,
    buyer_signature VARCHAR2(100) NOT NULL,
    signed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    contract_hash VARCHAR2(64) NOT NULL, -- Cryptographic seal for compliance
    ledger_index_id VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_contract_deal FOREIGN KEY (deal_id) REFERENCES deals(deal_id) ON DELETE CASCADE
);

-- 14. PAYMENTS RECORDS (PLATFORM BILLING ONLY)
CREATE TABLE payments (
    payment_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19, 0) NOT NULL,
    user_email VARCHAR2(255) NOT NULL,
    order_id VARCHAR2(100) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR2(100) UNIQUE,
    amount NUMBER(19, 2) NOT NULL,
    currency VARCHAR2(10) DEFAULT 'INR' NOT NULL,
    status VARCHAR2(30) NOT NULL, -- CREATED, CAPTURED, FAILED
    plan_type VARCHAR2(100) NOT NULL, -- Creator Monthly, Creator Annual, Buyer Monthly, Buyer Annual
    subscription_type VARCHAR2(50) NOT NULL, -- CR_MONTHLY, CR_ANNUAL, BY_MONTHLY, BY_ANNUAL
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_payments_order ON payments(order_id);

-- 15. NOTIFICATIONS
CREATE TABLE notifications (
    notification_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR2(255) NOT NULL,
    category VARCHAR2(50) NOT NULL, -- DEAL_UPDATE, SCREENER_REQUEST, USER_APPROVAL, PAYMENT_SUCCESS
    message VARCHAR2(1000) NOT NULL,
    is_read NUMBER(1, 0) DEFAULT 0 NOT NULL, -- 0 = False, 1 = True
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_notif_recipient ON notifications(recipient_email);

-- 16. SEGREGATED SECURE AUDIT LOG
CREATE TABLE audit_logs (
    log_id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    username VARCHAR2(255) NOT NULL,
    role VARCHAR2(30) NOT NULL,
    action VARCHAR2(100) NOT NULL, -- LOGIN, UPLOAD, DOWNLOAD, deal operations, payments
    details VARCHAR2(4000) NOT NULL,
    oracle_hash VARCHAR2(64) NOT NULL -- SHA-256 seal mimicking block audit validation integrity
);

CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_time ON audit_logs(timestamp);
